In [8]:
import pandas as pd
df1 = pd.read_csv("the_numbers_actors.csv")
df2 = pd.read_csv("the_numbers_scrap.csv")

In [9]:
df1

                                           title                actor  year
0                                 Captain Marvel          Brie Larson  2019
1                                 Captain Marvel    Samuel L. Jackson  2019
2                                 Captain Marvel       Ben Mendelsohn  2019
3                                 Captain Marvel       Djimon Hounsou  2019
4                                 Captain Marvel             Lee Pace  2019
5                                 Captain Marvel        Lashana Lynch  2019
6                                 Captain Marvel           Gemma Chan  2019
7                                 Captain Marvel       Annette Bening  2019
8                                 Captain Marvel          Clark Gregg  2019
9     How to Train Your Dragon: The Hidden World         Jay Baruchel  2019
10                                         Glass         James McAvoy  2019
11                                         Glass         Bruce Willis  2019
12                                         Glass    Samuel L. Jackson  2019
13                                    The Upside           Kevin Hart  2019
14                                    The Upside       Bryan Cranston  2019
15             The LEGO Movie 2: The Second Part          Chris Pratt  2019
16             The LEGO Movie 2: The Second Part      Elizabeth Banks  2019
17             The LEGO Movie 2: The Second Part          Will Arnett  2019
18             The LEGO Movie 2: The Second Part      Tiffany Haddish  2019
19             The LEGO Movie 2: The Second Part    Stephanie Beatriz  2019
20             The LEGO Movie 2: The Second Part          Alison Brie  2019
21             The LEGO Movie 2: The Second Part        Nick Offerman  2019
22             The LEGO Movie 2: The Second Part          Charlie Day  2019
23                                            Us       Lupita Nyong'o  2019
24                           Alita: Battle Angel         Rosa Salazar  2019
25                           Alita: Battle Angel      Christoph Waltz  2019
26                           Alita: Battle Angel    Jennifer Connelly  2019
27                           Alita: Battle Angel       Mahershala Ali  2019
28                           Alita: Battle Angel            Ed Skrein  2019
29                           Alita: Battle Angel   Jackie Earle Haley  2019
...                                          ...                  ...   ...
5353                    Die geliebten Schwestern  Henriette Confurius  2015
5354                           Beyond the Lights      Gugu Mbatha-Raw  2015
5355                           Beyond the Lights          Nate Parker  2015
5356                               Shao nian ban          Sun Honglei  2015
5357                               Shao nian ban          Dongyu Zhou  2015
5358                               Shao nian ban          Zijian Dong  2015
5359                               Shao nian ban          Wang Yuexin  2015
5360                               Shao nian ban          Li-Xin Zhao  2015
5361                               Shao nian ban            Cici Wang  2015
5362                                       Aloft    Jennifer Connelly  2015
5363                                      Loreak         Itziar Ituno  2015
5364                                      Loreak      Nagore Aranburu  2015
5365                          We Come as Friends        Hubert Sauper  2015
5366                          We Come as Friends    Barney Broomfield  2015
5367                          We Come as Friends        Ross Turnbull  2015
5368                          We Come as Friends       Xavier Liebard  2015
5369                                       Heist  Jeffrey Dean Morgan  2015
5370                                       Heist       Robert De Niro  2015
5371                                       Heist        Kate Bosworth  2015
5372                                       Heist        Dave Bautista  2015
5373                                      Spring     Lou Taylor Pucci  2015
5374                                      Spring         Nadia Hilker  2015
5375                                      Difret         Meron Getnet  2015
5376                                      Difret        Tizita Hagere  2015
5377                                 Red Herring  Robert Scott Howard  2015
5378                                 Red Herring        Holly Valance  2015
5379                                 Red Herring          Chyna McCoy  2015
5380                                 Red Herring        G. Eric Miles  2015
5381                                 Red Herring           Tim Tucker  2015
5382                                 Red Herring      Vincent Pastore  2015

[5383 rows x 3 columns]

In [10]:
df2

,rank_in_year,title,year,genre,gross,budget
0,1,Captain Marvel,2019,Action,"$323,646,033","$152,000,000"
1,2,How to Train Your Dragon: The Hidden World,2019,Adventure,"$147,460,290","$129,000,000"
2,3,Glass,2019,Thriller/Suspense,"$110,861,630","$20,000,000"
3,4,The Upside,2019,Comedy,"$106,984,792","$37,500,000"
4,5,The LEGO Movie 2: The Second Part,2019,Adventure,"$103,762,494","$99,000,000"
5,6,Us,2019,Thriller/Suspense,"$85,106,185","$24,600,000"
6,7,Alita: Battle Angel,2019,Action,"$83,956,461",NaN
7,8,Aquaman,2019,Action,"$74,802,530","$160,000,000"
8,9,Tyler Perry's A Madea Family Funeral,2019,Comedy,"$66,688,573",NaN
9,10,Spider-Man: Into The Spider-Verse 3D,2019,Adventure,"$55,923,345","$90,000,000"
10,11,Bumblebee,2019,Adventure,"$55,769,470","$102,000,000"
11,12,What Men Want,2019,Comedy,"$54,085,444","$20,000,000"
12,13,Green Book,2019,Comedy,"$48,837,730","$28,900,000"
13,14,Isn't it Romantic,2019,Romantic Comedy,"$47,691,683","$31,000,000"
14,15,A Dog's Way Home,2019,Drama,"$41,952,715",NaN
15,16,The Mule,2019,Drama,"$39,084,073","$50,000,000"
16,17,Escape Room,2019,Thriller/Suspense,"$38,467,985",NaN
17,18,Mary Poppins Returns,2019,Musical,"$33,014,229","$130,000,000"
18,19,Cold Pursuit,2019,Thriller/Suspense,"$31,854,994",NaN
19,20,Dragon Ball Super: Broly,2019,Action,"$30,376,755","$8,500,000"
20,21,Wonder Park,2019,Adventure,"$30,049,734","$100,000,000"
21,22,Five Feet Apart,2019,Drama,"$28,145,448","$7,000,000"
22,23,Happy Death Day 2U,2019,Thriller/Suspense,"$27,892,355","$9,000,000"
23,24,Bohemian Rhapsody,2019,Drama,"$26,143,592","$55,000,000"
24,25,Fighting With My Family,2019,Comedy,"$22,028,635","$11,000,000"
25,26,On the Basis of Sex,2019,Drama,"$20,914,838","$20,000,000"
26,27,The Favourite,2019,Black Comedy,"$18,267,686","$15,000,000"
27,28,Vice,2019,Black Comedy,"$18,093,238","$60,000,000"
28,29,The Kid Who Would Be King,2019,Adventure,"$16,780,002","$59,000,000"
29,30,Miss Bala,2019,Action,"$14,998,027","$15,000,000"
...,...,...,...,...,...,...
2160,471,Eden,2015,Drama,"$65,460",NaN
2161,472,National Gallery,2015,Documentary,"$64,597",NaN
2162,473,E gun tian shi,2015,Comedy,"$64,470",NaN
2163,474,Hua Li Shang Ban Zou,2015,Musical,"$63,029",NaN
2164,475,Drunk Stoned Brilliant Dead The Story of the N...,2015,Documentary,"$62,684",NaN
2165,476,Only You,2015,Romantic Comedy,"$61,565",NaN
2166,477,Dark Star: H.R. Giger's World,2015,Documentary,"$61,303",NaN
2167,478,Bande de filles,2015,Drama,"$60,765",NaN
2168,479,The Pyramid,2015,Horror,"$60,598",NaN
2169,480,GÃ¼eros,2015,Comedy,"$60,171",NaN
2170,481,Cooties,2015,Black Comedy,"$60,058",NaN
2171,482,I Smile Back,2015,Drama,"$58,738",NaN
2172,483,Jauja,2015,Drama,"$58,403",NaN
2173,484,Du rififi chez les hommes,2015,Thriller/Suspense,"$57,749",NaN
2174,485,Brian Wilson: I Just Wasn't Made for These Times,2015,Documentary,"$56,744",NaN
2175,486,The Duke of Burgundy,2015,Drama,"$56,657",NaN
2176,487,The Judge,2015,Drama,"$56,282","$50,000,000"
2177,488,Antarctica: A Year on Ice,2015,Documentary,"$54,710","$1,000,000"
2178,489,Die geliebten Schwestern,2015,Drama,"$54,064",NaN
2179,490,Beyond the Lights,2015,Drama,"$54,018","$7,000,000"
2180,491,Shao nian ban,2015,Comedy,"$53,252",NaN
2181,492,Aloft,2015,Drama,"$53,086","$8,000,000"
2182,493,The Quay Brothers in 35MM,2015,Documentary,"$51,858",NaN
2183,494,Loreak,2015,Drama,"$51,238",NaN
2184,495,We Come as Friends,2015,Documentary,"$50,921",NaN
2185,496,The Yes Men Are Revolting,2015,Documentary,"$50,190",NaN
2186,497,Heist,2015,Thriller/Suspense,"$50,136","$8,900,000"
2187,498,Spring,2015,Horror,"$49,970",NaN
2188,499,Difret,2015,Drama,"$49,667",NaN
2189,500,Red Herring,2015,Drama,"$49,480",NaN